### ISSUE TITLE
Launcher Development Log

### ISSUE THREAD

**Issue by BSDE-xSirBlockx** [BSDE-xSirBlockx/ACLauncher#2]
### All things that are needed for the launcher to run are finished, in later updates there will be features like things that you can read below 

> PRIORITY
- [x] Redesign the launcher so its fancy and Newcomer appealing
- [ ] Language Change Option for the Launcher (while at settings menu)
- [ ] Dark and Light Theme option in settings menu
- [x] Map showcase menu & picture previews leading to a detailed description site + auto download
- [x] Upload selfmade maps to AdventureCraft servers (what are requirements to publish it?)

> LATER
- [x] Version selection e.g. (1.12.2 - AC / 1.15.2 - AC when ready / maybe old AC)
- [x] A button to install the old AC Version (Checklist for maps that should download with it)

> FINISHED
- [x] Settings menu (e.g. Console & Java Settings (e.g. amount of RAM and JAVA Path & (once doable add Java Argument box))) - Inspired by Helios Launcher
- [x] Make the launcher move maps on update
- [x] AdventureCraft Background Picture maybe?
- [x] Get rid of Bootstrap in the Login Menu
- [x] Make pictures not draggable
- [x] Make most things like pictures local for people with bad internet
- [x] Make Launcher dragable
- [x] Wait until game is loaded and then close launcher
- [x] Detailed changelog in launcher
- [x] Navigation Buttons to access the map folder
- [x] Button to self minimize the launcher
- [x] Notificate the user about updates instead of doing them in the background
- [x] When Game gets closed kill launcher background process
- [x] Find out why adventurecraft sometimes doesnt load the main mod
- [x] Authenticate with mojang servers
- [x] Stay logged in
- [x] Launcher update mechanism

**Comment by TheDazze** [comment]
I'd like an Item for the camera edit (Just as the NPC Stick, but maybe with a different style and for cameras of course). Like adding Viewpoints (instead of /cameraadd), changing tracks more easily (If you have 2 camerablocks nearby, it's kinda difficult to swap between them) and maybe a way to switch modes (Game pausing/Game running) in the Same Track (e.g. Point 1 & 2 freeze the game, but at Point 3, it runs again. And if we're here: maybe not where the points are, but typing a time and at that time, it switches. That means, although Point 2 is Time 4 seconds and Point 3 is 10 seconds, you can say, the gamemode changes at 7 seconds.).
To understand Everything better, here are some pictures I made myself:
http://prntscr.com/pgk5gn 
That's the tool

http://prntscr.com/pgl4gr
This is the Menu...
