### ISSUE TITLE
Why does it need admin perms every time I launch this?

### ISSUE THREAD

**Issue by iceypotato** [BSDE-xSirBlockx/ACLauncher#23]
I don't understand why the Adventure Craft Awakening launcher needs admin permission to run every single time. Although it's most likely not a virus, It raises my suspicion. Also, MC Launcher does not need admin permissions to run, so why does this need it?

**Comment by BSDE-xSirBlockx** [comment]
It needs admin perms cause if you install in programs folder, electron can't access anything or write anyhing in the programs folder.
Because some people want to choose where to install AdventureCraft and also do this sometimes in the programs folder and had issues with that, we decided to let AdventureCraft always start with admin perms

**Comment by iceypotato** [comment]
Maybe the preferences and data should be put in the user's %appdata% folder, so every user on the computer can play it and have their own data. Also, I realized that my password was in plain text when I opened the config file. Can you encrypt it or something?

**Comment by BSDE-xSirBlockx** [comment]
The %appdata% option is not possible because we can't actually access the old AdventureCraft from there where is also data in it, and we can't rewrite it.

We had several options for the password

- Send it to mojang and just save the token we get back for logging in, then there would be no raw password
- But we thought it's annoying to always login new if you logged in into normal MC Launcher where you generate a new token. And you would have to login again in AC Launcher too

This is especially annoying when you are programming sth new and try out several stuff so you would have to login in a thousand times...
