### ISSUE TITLE
Camera Block

### ISSUE THREAD

**Issue by BSDE-xSirBlockx** [BSDE-xSirBlockx/ACLauncher#8]
I'd like an Item for the camera edit (Just as the NPC Stick, but maybe with a different style and for cameras of course). Like adding Viewpoints (instead of /cameraadd), changing tracks more easily (If you have 2 camerablocks nearby, it's kinda difficult to swap between them) and maybe a way to switch modes (Game pausing/Game running) in the Same Track (e.g. Point 1 & 2 freeze the game, but at Point 3, it runs again. And if we're here: maybe not where the points are, but typing a time and at that time, it switches. That means, although Point 2 is Time 4 seconds and Point 3 is 10 seconds, you can say, the gamemode changes at 7 seconds.).
To understand Everything better, here are some pictures I made myself:
http://prntscr.com/pgk5gn 
That's the tool

http://prntscr.com/pgl4gr
This is the Menu...

_Originally posted by @TheDazze in https://github.com/BSDE-xSirBlockx/AdventureCraft/issues/2#issuecomment-539637825_

**Comment by AC-Drifter** [comment]
### As I can see someone has some idea with control at Camera entity, so my issue about it here to supplement it.
**"Camera** **Block"** which:
 -can add|delete "new" Cameras easily (by one button) 
-can changing (or) controlling Cameras (and the same as @BSDE-xSirBlockx idea to make cameras change directions of view, "How can camera moving fast." or "how much longer it going to show.")
_(My idea about (new)_ buttons:
 Place|add "Player Static Camera" (Making Camera Look only at one direction);
Place|add "Observing|Moving Static Camera" (observing|following at player, also works like F5 "third-person view mode", but can be controlled (or) changed for any length and distance or use only one of them).)
When "Map Editor" using "Debug Mode", then these _"Camera effects"_ doesn't react at player until "Debug Mode" be turn off.
**My Idea to supplement @BSDE-xSirBlockx issue about "Camera Block" and his new features will give "Map Editors" more possibilities with (new|advanced) camera, "Cutscenes with NPCs", "Static|Moving Gameplay Cameras" and much more... I'll hope this Idea will be useful, because it will make "AC" much unique and give much more possibilities to create in this "game".**
_Thanks in Advance!_

**Comment by Ladackii** [comment]
Some nice points there. Just wanted to say: My intention wasn't to change their direction of view, but whether you can control the player or not at certain times. But yeah, the camera tool / camera block needs an update for sure.
